spring.application.name=hses

# 0. Import biến môi trường từ file .env (nếu có)
spring.config.import=optional:file:.env[.properties]

# 1. Cổng chạy của Server
server.port=8080

# 2. Cấu hình Database SQL Server
spring.datasource.url=${DB_URL:jdbc:sqlserver://localhost:1433;databaseName=hanoiprep_db;encrypt=true;trustServerCertificate=true;sendStringParametersAsUnicode=true;useUnicode=true;characterEncoding=UTF-8;}
spring.datasource.username=${DB_USERNAME:sa}
spring.datasource.password=${DB_PASSWORD:sa}
spring.datasource.driver-class-name=com.microsoft.sqlserver.jdbc.SQLServerDriver

# 3. Cấu hình Hibernate cho SQL Server
spring.jpa.hibernate.ddl-auto=update
spring.jpa.show-sql=true
spring.jpa.properties.hibernate.dialect=org.hibernate.dialect.SQLServerDialect

# 4. Cấu hình kết nối RabbitMQ
spring.rabbitmq.host=localhost
spring.rabbitmq.port=5672
spring.rabbitmq.username=guest
spring.rabbitmq.password=guest
spring.rabbitmq.listener.simple.concurrency=1
spring.rabbitmq.listener.simple.max-concurrency=1

# 5. Cấu hình Google Gemini API Key
gemini.api.key=${GEMINI_API_KEY:}
spring.ai.google.genai.api-key=${gemini.api.key}

# 6. Cấu hình JWT
hses.app.jwtSecret=${JWT_SECRET:SGFub2lQcmVwSFNFU1NlY3JldEtleUZvckp3dFRva2Vuc0hhbm9pUHJlcEhTRVNTZWNyZXRLZXlGb3JKd3RUb2tlbnMyMDI2}
hses.app.jwtExpirationMs=86400000

# 7. Cấu hình Multipart Upload File
spring.servlet.multipart.max-file-size=50MB
spring.servlet.multipart.max-request-size=50MB

# 8. Cấu hình Cloudinary
cloudinary.cloud_name=${CLOUDINARY_CLOUD_NAME:}
cloudinary.api_key=${CLOUDINARY_API_KEY:}
cloudinary.api_secret=${CLOUDINARY_API_SECRET:}