spring.application.name=hses
# 1. Cổng chạy của Server
server.port=8080

spring.datasource.url=jdbc:sqlserver://localhost:1433;databaseName=hanoiprep_db;encrypt=true;trustServerCertificate=true;sendStringParametersAsUnicode=true;useUnicode=true;characterEncoding=UTF-8;
spring.datasource.username=sa
spring.datasource.password=sa
spring.datasource.driver-class-name=com.microsoft.sqlserver.jdbc.SQLServerDriver

# 3. Cấu hình Hibernate cho SQL Server
spring.jpa.hibernate.ddl-auto=update
spring.jpa.show-sql=true
spring.jpa.properties.hibernate.dialect=org.hibernate.dialect.SQLServerDialect

# 4. Cấu hình kết nối RabbitMQ
spring.rabbitmq.host=localhost
spring.rabbitmq.port=5672
spring.rabbitmq.username=guest
spring.rabbitmq.password=guest
spring.rabbitmq.listener.simple.concurrency=1
spring.rabbitmq.listener.simple.max-concurrency=1

# 5. Cấu hình Google Gemini API Key
gemini.api.key=AQ.Ab8RN6LpnY5QGx6sDWxwyMEUbUm1DScYgn9jDlmGAfFZ0ETISw
spring.ai.google.genai.api-key=${gemini.api.key}

# 6. Cấu hình JWT
hses.app.jwtSecret=SGFub2lQcmVwSFNFU1NlY3JldEtleUZvckp3dFRva2Vuc0hhbm9pUHJlcEhTRVNTZWNyZXRLZXlGb3JKd3RUb2tlbnMyMDI2
hses.app.jwtExpirationMs=86400000

# 7. Cấu hình Multipart Upload File
spring.servlet.multipart.max-file-size=50MB
spring.servlet.multipart.max-request-size=50MB

# 8. Cấu hình Cloudinary
cloudinary.cloud_name=dxgpvv5kf
cloudinary.api_key=966155831811553
cloudinary.api_secret=VV-IpW-OuSew9XRxJOzugJcCXSY